services:
  library-events:
    build:
      context: ./vbkg_server
      dockerfile: vbkg.Dockerfile
    image: library-events
    container_name: library-events-container
    expose:
      - "3000"  # Проброс порта внутри сети Docker
    # Используем переменные окружения из .env
    env_file:
      - .env
    environment:
      # Виртуальный хост сервера
      - VIRTUAL_HOST
      # Хост для сертификации acme-companion
      - LETSENCRYPT_HOST
      # Почта для сертификации
      - LETSENCRYPT_EMAIL
      # Порт
      - PORT
      # Пароль администратора
      - ADMIN_PASSWORD_HASH
      # Ключ JWT
      - JWT_SECRET
      # URL фронтенд-статики
      - FRONTEND_URL
    volumes:
      # Монтируем том для хранения данных
      - db_data:/usr/src/app/data
      # Монтируем .env файл из хост-системы
      - .env:/usr/src/app/server/.env
      # Монтируем том для хранения изображений
      - server_uploads:/usr/src/app/server/uploads    
    restart: unless-stopped

  nginx-proxy: # Прокси-сервер nginx-proxy для работы с acme-companion
    build:
      context: ./nginx-proxy
      dockerfile: nginx-proxy.Dockerfile
    container_name: nginx-proxy
    depends_on:
      - library-events
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Том для хранения сертификатов
      - certs:/etc/nginx/certs
      # Том для хранения виртуальных хостов
      - vhost:/etc/nginx/vhost.d
      # Том для хранения статики
      - html:/usr/share/nginx/html
    restart: unless-stopped

  acme-companion: # Контейнер автоматической сертификации
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    # Используем переменные окружения из .env
    env_file:
      - .env
    environment:
      # Почта для сертификации
      - LETSENCRYPT_EMAIL
    volumes_from:
      # Подключаем томы из nginx-proxy
      - nginx-proxy
    volumes:
      # Том для docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Том для хранения сертификатов
      - certs:/etc/nginx/certs
      # Том для хранения виртуальных хостов для сертификации
      - vhost:/etc/nginx/vhost.d
      # Том для хранения статики
      - html:/usr/share/nginx/html
      # Том для хранения acme-скриптов
      - acme:/etc/acme.sh
    restart: unless-stopped

volumes:
  acme:
  certs:
  vhost:
  html:
  db_data:
    name: library-events-db-data
  server_uploads:
    name: library-events-server-uploads
