name: Production Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Настройка SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Настройка known hosts
      - name: Ensure Known Hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Синхронизирование файлов
      - name: Rsync to Server
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'backup_*.tar.gz' \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/vbkg/

      # Настройка .env
      - name: Setup .env
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            
            set -e

            cd "\$HOME/vbkg"

            touch .env

            update_env_var () {
              VAR_NAME=\$1
              VAR_VALUE=\$2
              if grep -q "^\${VAR_NAME}=" .env; then
                sed -i "s|^\${VAR_NAME}=.*|\${VAR_NAME}=\${VAR_VALUE}|" .env
              else
                echo "\${VAR_NAME}=\${VAR_VALUE}" >> .env
              fi
            }

            update_env_var "VIRTUAL_HOST" "${{ secrets.VIRTUAL_HOST }}"
            update_env_var "LETSENCRYPT_HOST" "${{ secrets.LETSENCRYPT_HOST }}"
            update_env_var "LETSENCRYPT_EMAIL" "${{ secrets.LETSENCRYPT_EMAIL }}"
            update_env_var "PORT" "${{ secrets.PORT }}"

            echo "Environment variables updated successfully."
          EOF

      # Создание бэкапа
      - name: Create Backup
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            
            set -e

            BASE_DIR="\$HOME/vbkg"
            TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
            BACKUP_FILE="backup_\${TIMESTAMP}.tar.gz"

            mkdir -p "\$BASE_DIR"
            cd "\$BASE_DIR"

            # Check if vbkg directory is not empty
            if [ "\$(ls -A . 2>/dev/null)" ]; then
              tar -cvzf "\$BACKUP_FILE" \
              --exclude="*.tar.gz" \
              ./
            fi

            echo "Backup created: \$BACKUP_FILE"
          EOF

      # Запуск контейнера
      - name: Deploy Docker Container
        id: deploy_step
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e
            cd ~/vbkg

            docker compose down
            docker compose up --build -d

            # Remove old backups (select all but the last one made)
            ls -t backup_*.tar.gz | tail -n +2 | xargs -r rm -f

            echo "Deployment completed."
          EOF

      # Rollback при ошибке
      - name: Rollback
        if: failure()
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/vbkg

            echo "Deployment failed. Starting rollback..."

            # Remove backup of last rsync
            ls -t backup_*.tar.gz | head -n 1 | xargs -r rm -f

            # Get the name of previous backup
            PREV_BACKUP=\$(ls -t backup_*.tar.gz | head -n 1)

            # Restore files from previous backup
            if [ -f "\$PREV_BACKUP" ]; then
              tar -vxzf "\$PREV_BACKUP"
              docker compose down || true
              docker compose up --build -d
              echo "Rollback completed."
            else
              echo "No backup found."
            fi
          EOF

      # Удаление фалов конфигурации
      - name: Clean Up
        if: always()
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/vbkg
            
            rm -f vbkg_server/vbkg-pr-cbs-ru-ssl.conf
            rm -f nginx-proxy/conf.d/nginx.conf
            rm -f .env

            echo "Cleanup completed."
          EOF
